language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-modular-project' ]; then cd .. && eval "mv $currentfolder generator-modular-project" && cd generator-modular-project; fi
